# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      working-directory: CodeChallenge
      run: dotnet build
    - name: Ensure browsers are installed
      working-directory: CodeChallenge/SpreeCommerce.Tests
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps chromium
    - name: Run your tests
      working-directory: CodeChallenge
      run: dotnet test --settings Playwright.runsettings -- Playwright.BrowserName=chromium Playwright.LaunchOptions.Headless=true -l "trx;LogFilePath=${{ github.workspace }}/TestResults/TestResults.trx"
      env:
       UITARGETENVIRONMENT: demo
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: (!cancelled())
      with:
        files: |
         ${{ github.workspace }}/TestResults/*.trx
