# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      working-directory: CodeChallenge
      run: dotnet build
    - name: Ensure browsers are installed
      working-directory: CodeChallenge/SpreeCommerce.Tests
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps chromium
    - name: Run your tests
      working-directory: CodeChallenge
      run: dotnet test --logger trx --settings "${{ github.workspace }}\CodeChallenge\Playwright.runsettings" --filter "FullyQualifiedName~SpreeCommerce.Tests" 
      env:
       UITARGETENVIRONMENT: demo
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
       name: test-artifacts
       path: ${{ github.workspace }}\CodeChallenge\SpreeCommerce.Tests\bin\**\TestScreenshots
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: (!cancelled())
      with:
        files: |
         ${{ github.workspace }}\CodeChallenge\SpreeCommerce.Tests\TestResults\*.trx
